### ISSUE TITLE
Licence needs to be enforced

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#1004]
Right now, the selecting licence part seems to be optional. We would want that to be enforce. Maybe disable the "next" button until they select one. 

<img width="512" alt="image" src="https://github.com/clowder-framework/clowder2/assets/13950475/ead2514b-f67e-439b-bc54-cfcc73af8a39">

This part is open discussion: for backward compatible, if nothing is set, could we default a licence for them? Thoughts?

**Comment by ddey2** [comment]
@longshuicy Thanks for noticing this. I think we should mandate it.
