### ISSUE TITLE
The “Description”

### ISSUE THREAD

**Issue by FyZoey** [clowder-framework/clowder2#1020]
**Key problem to be solved:**
The user didn’t realize that the description is there

Current interface:
<img width="1552" alt="Screenshot 2024-04-09 at 10 15 1" src="https://github.com/clowder-framework/clowder2/assets/65145184/620646b1-7045-4853-b0b2-abf548ecc6d7">

**Suggestions:**
Modify the appearance of text
1. Switch the display sequence of “authorship” and the “description”, make the “authorship” a bit smaller, so that leaving more spaces between different blocks of text
2. Change the text of description in gray, align to the left with the extractor title

**Suggested design:**
<img width="1552" alt="Group 23" src="https://github.com/clowder-framework/clowder2/assets/65145184/8ade7dc9-8eb6-4592-85a2-43a50c7af72b">
<img width="1552" alt="Group 22" src="https://github.com/clowder-framework/clowder2/assets/65145184/accf39cc-360e-48a0-a42b-3daa02a90576">

**Comment by Vismayak** [comment]
@FyZoey Hi Fangyu, I have aligned the description text with the extractor title. However the grey color is used as description for extractors that might be malfunctioning and cant be used. 

The blue text is used for those that are working and can be utilized by the user. I have attached a screenshot for your reference, would you still recommend switching to gray (or another color) for the description then. Or should we keep the color as it it?

![image](https://github.com/clowder-framework/clowder2/assets/16596733/ce7561c9-1398-463d-9837-e1a955fd714f)

**Comment by FyZoey** [comment]
I believe this is a technical issue that could be fixed since the color of a description shouldn't be attached to the color of the icon. Please check it again and revise the color of the text part of a description only. @lmarini please let me know if I misunderstood.

**Comment by FyZoey** [comment]
oops sorry I found I misunderstood your previous comment!!! I've just noticed that the first extractor you showed was a disabled one. 

For the disabled extractor, I'd recommend to use a lighter gray for all 3 elements: extractor name, description, and the play icon. 

But for the enabled extractor, the blue color name can say that this is activated already, the gray color description is just for telling people the description part is not clickable. The blue extractor name and play icon says "we are clickable". And since the description for the activated extractor uses a darker gray, it should be fine for telling people this is not "disabled". 

Please let me know if you want to discuss more about this!!
