### ISSUE TITLE
History - the version chip

### ISSUE THREAD

**Issue by FyZoey** [clowder-framework/clowder2#1021]
The version chip is not clickable for now, seems like a bug

<img width="1552" alt="Screenshot 2024-03-25 at 3 16 3" src="https://github.com/clowder-framework/clowder2/assets/65145184/f3bf601b-1ac2-4f11-b93c-0bb59c069227">

**Comment by lmarini** [comment]
We probably should just remove it from the table since it doesn't really add much useful info. @longshuicy
