### ISSUE TITLE
Miss aligned radio buttons for choosing license in Chrome

### ISSUE THREAD

**Issue by ddey2** [clowder-framework/clowder2#1029]
It's seen
![Screenshot 2024-04-25 at 3 50 26 PM](https://github.com/clowder-framework/clowder2/assets/22405928/e8a37014-0946-4e7e-a87c-382da4911172)
 in Chrome

**Comment by nitin-pandita** [comment]
Hey @ddey2 If you are not working on this issue i would like to give it a try

**Comment by ddey2** [comment]
@nitin-pandita Hi Nitin, this is taken care of. feel free to work on nay unassigned issue.

**Comment by nitin-pandita** [comment]
@ddey2  sure thing! Thank you for responding
