### ISSUE TITLE
Footer compressed on the create dataset page

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#1036]
The footer on the new dataset page appears to be compressed and improperly aligned on the right side. All the other routes seem fine.

<img width="1792" alt="image" src="https://github.com/clowder-framework/clowder2/assets/13950475/92e803e9-1aa5-49de-b2e1-67906efe34e3">

**Comment by ddey2** [comment]
I don't see the issue anymore on current main branch. I think using mui everywhere probably resolved the issue.
