### ISSUE TITLE
error shown when sharing dataset with user

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder2#1078]
If you share a dataset with a user, once you click "share" it shows the error message. But the user has been successfully added.

Here is a video that shows the bug:

**Comment by tcnichol** [comment]
https://github.com/clowder-framework/clowder2/assets/40038535/bccf996f-e5e3-48d8-91ba-b517a8c7d5bc

**Comment by longshuicy** [comment]
Since you have a PR for that, moving this to beta3
