### ISSUE TITLE
switch to rjsf/mui

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#1087]
Right now we are using [@rjsf/material-ui](https://www.npmjs.com/package/@rjsf/material-ui) which causing the style conflicts since we have material ui and mui at the same time
Try this library [@rjsf/mui](https://www.npmjs.com/package/@rjsf/mui) instead

**Comment by ddey2** [comment]
@longshuicy I updated it in all the places in #1056 and it's merged. 

I removed rjsf/material-ui from the frontend/package.json. I think we can close this issue.
