### ISSUE TITLE
Page is stuck if we try to download a dataset which contains big files

### ISSUE THREAD

**Issue by ddey2** [clowder-framework/clowder2#1119]
I tried downloading a dataset containing around 4GB file. Might want to confirm the same for files. 

This is in dev mode. Looks like the creation of zip is taking over the thread in the backend. Maybe it's not async?

**Comment by ddey2** [comment]
I installed aiofiles to asynchronously handle file operations. Still it's taking a little bit of time to prepare the zip file, then the download steaming is handled by the browser. The page is not stuck anymore. will soon create a PR. 
TODO
1. For future, we might want to separate the call to prepare zip file and actual download. 
2. Show users a snackbar that it might take a while to download
3. We create a temp file for the download. After the download, we should delete it.

**Comment by tcnichol** [comment]
@ddey2 is there a branch for this issue? Luigi asked me to take a look at this as well.
