### ISSUE TITLE
Enable admin mode switch to "mine"

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#1123]
On the latest main branch I noticed this behaviour:
1. Drop Admin mode
2. Enable again; instead of showing all the dataset, now I only see my own. Refresh doesn't help either. 

I see multiple request to the backend with mine flag fluctuated from false to true
<img width="1532" alt="image" src="https://github.com/clowder-framework/clowder2/assets/13950475/5600ec49-2ff6-4cf2-8260-d2dea8f43f49">

<img width="294" alt="image" src="https://github.com/clowder-framework/clowder2/assets/13950475/81e4d384-b95f-4433-a5f3-5d2de7132d94">

**Comment by tcnichol** [comment]
Will check.

**Comment by tcnichol** [comment]
I think this is fixed.

I enabled admin mode. Instead of 11 pages, I now see 14 pages of datasets.

Dropped admin mode. Now I see 11 pages.

Enabled again. Bottom shows a total of 14 pages.

I noticed that the datasets on the first page did not change though.

**Comment by tcnichol** [comment]
https://github.com/clowder-framework/clowder2/pull/1104

This branch is what I checked.

**Comment by longshuicy** [comment]
This is addressed in #1104
