### ISSUE TITLE
[Bug] Error creating a list entry in Metadata Definition

### ISSUE THREAD

**Issue by arunapa** [clowder-framework/clowder2#177]
I created an entry that includes a list but the list doesn't work when I try to create an instance of it. Just one field of type list. This is the definition in Mongo:

{ "_id": { "$oid": "635ff6063230ca72094d85d7" }, "name": "Abstract", "description": "Just another abstract", "context": { "abstract": "http://purl.org/dc/terms/abstract" }, "context_url": null, "fields": [ { "id": { "$oid": "635ff6063230ca72094d85d8" }, "name": "Abstract", "list": false, "widgetType": "Select", "config": { "id": { "$oid": "635ff6063230ca72094d85da" }, "type": "enum" }, "required": false } ], "creator": { "id": { "$oid": "632b39f29b06a45e416a33f4" }, "email": "lmarini@illinois.edu", "first_name": "Luigi", "last_name": "Marini" }}

https://github.com/clowder-framework/clowder2/pull/150#pullrequestreview-1162178917

**Comment by arunapa** [comment]
One improvement: Instead of having "Is List" we can rename it as "Allow Many" to convey the intent more clearly

**Comment by longshuicy** [comment]
Dropdown with Enum type still doesn't work. I will take a dab on that one.
