### ISSUE TITLE
same result appears multiple times when searching elasticsearch

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#185]
> 1. I searched for 'dataset' in searchbox and the same results appear multiple times. I checked the elasticsearch index and there are only 4 entries for datasets.  One reason could be, they had been updated and the search result show all of the combinations. Do we want that?

**Comment by lmarini** [comment]
@ddey2 we couldn't reproduce. Do you still see this?

**Comment by lmarini** [comment]
Could not reproduce.
