### ISSUE TITLE
Metadata definition creation misc bugs

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#197]
two bugs found:
1. date/time doesn't work
<img width="592" alt="image" src="https://user-images.githubusercontent.com/13950475/201718128-e91fdc10-d62b-4581-84a8-5efe1cf90142.png">

To reproduce, try create date time picker and select date or time as the required type

2. on the metadata tab; creating new definition leads to an empty page
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/13950475/201718405-d8e55a36-9f18-4837-90d0-5910bf77a3a1.png">

**Comment by arunapa** [comment]
@longshuicy I was playing around with the MetadataTimePicker component code and it seems to be out-of-date. The [code](https://github.com/clowder-framework/clowder2/blob/main/frontend/src/components/metadata/widgets/MetadataDateTimePicker.tsx#L2-L3) is using `@mui/lab` which should be migrated as per this guide https://mui.com/x/react-date-pickers/migration-lab/.

I was able to follow the migration guide and referring to the documentation, I was able to fix the render issue

![Screen Shot 2022-11-21 at 10 21 49 AM](https://user-images.githubusercontent.com/28983148/203105878-6428cbb7-0a65-4e5b-b9ac-295c3c142772.png)

**Comment by lmarini** [comment]
> 

Thanks @arunapa . Will you be making a PR for it?
