### ISSUE TITLE
fix hardcoding pieces in helm chart

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#200]
- [x] different username/password for minio fails, hardcoded username/password in backend?
- [x]  allow to configure keycloak #191 
- [x]  setup externalsecrets as a way to not hardcode the secrets in the helm chart.

**Comment by lmarini** [comment]
See docker-compose for how to initialize realm:

```
    volumes:
      - ./scripts/keycloak/clowder-realm-prod.json:/opt/keycloak/data/import/realm.json:ro
      - ./scripts/keycloak/clowder-theme/:/opt/keycloak/themes/clowder-theme/:ro
    command:
      - start-dev
      - --http-relative-path /keycloak
      - --import-realm
```
