### ISSUE TITLE
style extractor page to match the mockup

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#236]
Initially start with: 
- list extractor page
- search box
- submit page

Mockup see here:
https://www.figma.com/file/5UkG4raDVAWdCxw4wqGylb/Extractor-V2?node-id=0%3A1&t=xGfO0WsbrYyBfRMT-0

**Comment by tcnichol** [comment]
@longshuicy can you share this with me on Figma? I'm using my university email account there.

**Comment by longshuicy** [comment]
https://www.figma.com/file/5UkG4raDVAWdCxw4wqGylb/Extractor-V2?node-id=49%3A8605&t=AxcAo0FARqy6eXr8-1
