### ISSUE TITLE
Byte size doesn't update on updating new file

### ISSUE THREAD

**Issue by ddey2** [clowder-framework/clowder2#238]
<img width="1471" alt="Screen Shot 2022-12-12 at 5 12 32 PM" src="https://user-images.githubusercontent.com/22405928/207178313-a4dd94ef-c7d4-49a4-a4ca-8486d1354b77.png">

1. Upload a file under a dataset.
2. Update that file. 
 Notice the bye size never updates

**Comment by longshuicy** [comment]
@ddey2 has this been addressed? Would you mind taking a look at this?
