### ISSUE TITLE
Read and display extractor logs on frontend

### ISSUE THREAD

**Issue by max-zilla** [clowder-framework/clowder2#261]

**Comment by max-zilla** [comment]
Extractor sends to RabbitMQ, which we write to MongoDB (maybe needs to be added).

How do we live update frontend page? Web sockets?

**Comment by arunapa** [comment]
Milestones:

- [x] Create custom components for the frontend to display (1) summary of job status, (2) detailed logs

- [ ] Interface the custom component with the backend endpoint to fetch the extractor latest status and logs

- [ ] Make the frontend responsive by using polling to automatically update the logs and status when there is a change in the backend

**Comment by arunapa** [comment]
![Screen Shot 2023-02-09 at 7 16 59 AM](https://user-images.githubusercontent.com/28983148/217823375-76707961-ec7e-4069-82ed-001ef9e4b2ea.png)

Current UI snapshot, will be further improved/fine-tuned before the feature is completed.
