### ISSUE TITLE
Endpoint to get logs by Job ID

### ISSUE THREAD

**Issue by max-zilla** [clowder-framework/clowder2#263]

**Comment by longshuicy** [comment]
GET /listeners/logs?limit=&skip=&
GET /listeners/logs/extractors/extractor_id?job_id=&status&user_id=&file_id=&dataset_id=&limit=&skip=
GET /listeners/logs/jobs/job_id?job_id=&status&user_id=&file_id=&dataset_id=&limit=&skip=&
