### ISSUE TITLE
Extractor metadata and file versioning

### ISSUE THREAD

**Issue by max-zilla** [clowder-framework/clowder2#266]

**Comment by max-zilla** [comment]
Add planned functionality for extractor metadata to carry over when file versions are updated. Check documentation for implementation plan

**Comment by max-zilla** [comment]
EXAMPLE USE CASE:
We have File v1 (apple.png), it gets Metadata from a User and an Extractor.
	- User tag: fruit
	- Extractor metadata for SHA256: checksum

Upload apples.png (with 2 apples)
	- what do we do? 
	- OPTIONS:
		a. we leave all metadata tied to v1. v2 has no metadata. we trigger any extractors (checksum) as if it was a new file.
		b. we bring metadata over to v2, but label it as "Generated on v1" so user knows it might need to be replaced. We don’t know if the extractor is an automatic one or a manual one, we don’t know if its data will still be correct or not.
		c. we don't bring any metadata over, v2 is blank and extractors would need to be re-run
		d. c, but only bring over User metadata

Keep in mind, we don’t need to support every bad user behavior.

We are currently planning OPTION B.
- retain metadata. show newest version if possible, but show metadata for older file versions with appropriate labeling.

**Comment by ddey2** [comment]
I started working on this. I realized that it's performing OPTION B already. 

I looked into depth and noticed that the file version is not updated to metadata table in mongoDB and get_metadata for file retrieves the last updated metadata. So, no checking of version is done. Need to discuss more in details if this satisfies our use case here.

**Comment by ddey2** [comment]
After discussion with @lmarini , next steps

1. update the version on updating metadata
2. Think about whether we want to keep track of all metadata versions, whether it makes sense

**Comment by ddey2** [comment]
Today's discussion a Clowder v2 meeting

1. We want to show latest available metadata for user metadata if the there is no respective metadata for current file version.
2. We don't want to show extractor metadata for old file versions. We always want to run the extractor automatically whenever there is a new file version - #276 
3. We probably want to keep record of old versions of metadata for user metadata as we do in case of extractor metadata - #277
