### ISSUE TITLE
pyclowder - add missing methods

### ISSUE THREAD

**Issue by max-zilla** [clowder-framework/clowder2#268]

**Comment by max-zilla** [comment]
- adding previews from extractors
- make sure file uploads are possible
- creation of new datasets / folders
- upload metadata
- deleting things
- trigger additional extractors

**Comment by max-zilla** [comment]
plan is to break this into smaller tasks.

**Comment by ddey2** [comment]
@tcnichol What's the status on this? Does the following PR has some of the functions?
https://github.com/clowder-framework/pyclowder/pull/60/files#diff-d63207a185aaa403ba2c2307ace959fdf97c150776df6ef44b1fd6ca93bd0b10

**Comment by tcnichol** [comment]
Change status and linked pull request.
