### ISSUE TITLE
update metadata extractors in extractors core

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder2#293]
Issue is this:
https://github.com/clowder-framework/extractors-core/issues/27

Adding a new extractor to v2 will allow for better testing of extractor features and we can add some as default extractors in a yml file.

**Comment by tcnichol** [comment]
Updating this will require some additional work.

The context field in metadata needs to be a list that can contain URL or dictionary to match json-ld specs. That will be done in clowderv2 with another pull request.

Pyclowder2 will need to be changed to match this as well.

**Comment by ddey2** [comment]
What's the status?

**Comment by tcnichol** [comment]
Changed status to in review and linked pull requests.

**Comment by ddey2** [comment]
Thanks @tcnichol
