### ISSUE TITLE
Upload new version button on file page

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#300]
Right now you can only upload a new version of a file from the dataset page, but not the file page.

**Comment by longshuicy** [comment]
<img width="1589" alt="image" src="https://user-images.githubusercontent.com/13950475/220163751-77f5dca4-bbaf-4add-a80d-9e1635cc4690.png">
right now you can only click this button

but maybe on the file page create a button called update and do the exact same thing
