### ISSUE TITLE
When session timesout uploads fail

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#301]
If the session times out and we are on the dataset page, we can still try to upload a new file/version but the upload component will fail with an error instead of refresh the token.

**Comment by longshuicy** [comment]
Might be related to elasticsearch time out issue #302

**Comment by arunapa** [comment]
@lmarini @longshuicy I tested this issue with the latest commit on main. I modified the keycloak SSO timeout to be 1 min. I am able to upload files now, even when the session times out. I was able to look at the API calls to verify that the token is being refreshed as well.

![Image](https://user-images.githubusercontent.com/28983148/222571614-b1f74595-c971-4ae8-b8bc-e6f352bd2608.png)

**Comment by arunapa** [comment]
The refresh token is retrieved once the popup to upload a new file opens up.
