### ISSUE TITLE
Refreshing session takes to home page

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#302]
When the JWT token expires, we refresh it for the user, but we don't currently take the user back to the page they were on. Ideally the page shouldn't refresh at all.

**Comment by longshuicy** [comment]
This might be harder to fix... all the refresh except the elasticsearch refresh happens silently. Only the elasticsearch refresh reload the page. But because the search bar is always on the top so it's basically on every single page

**Comment by longshuicy** [comment]
1. remove the search on the topbar --> searchbox that takes to the search page with query parameter --> maybe I can redirect to the search page??

2. Optional 2: instead of automatically refresh just show the error (there is error boundary there)
