### ISSUE TITLE
Download older version of a file

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#303]
Add link to download older version of a file.

**Comment by longshuicy** [comment]
Do we have backend support for this task?

**Comment by max-zilla** [comment]
> Do we have backend support for this task?

No, in routes/files download_file currently just accepts file ID, for this we'll need a version parameter as well.

**Comment by longshuicy** [comment]
Me and @ddey2 can make an attempt to create the download link on the frontend if it's quick
