### ISSUE TITLE
add loading spinner for "Update" the file

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#332]
We may need the same thing for "update" the file. This could be another task next. Thanks!

_Originally posted by @longshuicy in https://github.com/clowder-framework/clowder2/issues/331#issuecomment-1433519057_

**Comment by arunapa** [comment]
@longshuicy It seems like this is already implemented in the code [here](https://github.com/clowder-framework/clowder2/blob/main/frontend/src/components/files/UpdateFile.tsx#L28-L33).

Also I tested in the UI -- I'm able to view it. Do we need to change the layout or can it stay as-is?
![Uploading Screen Shot 2023-02-22 at 4.49.11 PM.png…]()

**Comment by longshuicy** [comment]
Oh really? that's awesome. Then maybe we can close this issue
