### ISSUE TITLE
fix metadata update

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder2#333]
update metadata throws an error. work to fix.

**Comment by tcnichol** [comment]
Below is the debugger when metadata is being added:
<img width="1153" alt="Screen Shot 2023-02-16 at 2 16 02 PM" src="https://user-images.githubusercontent.com/40038535/219482554-b4d36907-f181-4a10-aba2-a013936bbb07.png">

And here is when it is being updated:

<img width="1144" alt="Screen Shot 2023-02-16 at 2 14 14 PM" src="https://user-images.githubusercontent.com/40038535/219482602-dd260c00-cff4-4cc5-b0cb-15156aa1856d.png">

So it looks like the problem is that instead of the key value being the name of the MetadataDefinition, it's the entire object?

**Comment by longshuicy** [comment]
Is this still an issue?

**Comment by ddey2** [comment]
This is fixed. Confirmed on main branch.
