### ISSUE TITLE
updating file gives wrong size

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder2#349]
When updating a file of approximately 20 MB or more, the size shown for the v2 after update is wrong.

**Comment by arunapa** [comment]
Before update:
![Screen Shot 2023-02-22 at 4 32 23 PM](https://user-images.githubusercontent.com/28983148/220783119-147fc1ed-f8c3-4471-a29e-63dde36d91eb.png)
After update:
![Screen Shot 2023-02-22 at 4 33 39 PM](https://user-images.githubusercontent.com/28983148/220783121-6a5ad729-3bad-489c-b4c1-7115489f6ef6.png)

**Comment by tcnichol** [comment]
Tested downloading the v2 file. It only downloads a partial file that is the incorrect size shown in v2.
