### ISSUE TITLE
How to handle viewing previous file versions

### ISSUE THREAD

**Issue by max-zilla** [clowder-framework/clowder2#366]
Metadata can be associated with a previous file version.

- Dropdown for the entire file view (V3... V2... V1) that changes all metadata tabs, description, the download button corresponds to that version, etc.

- Dropdown just for metadata tab that lets you view previous version of metadata without affecting other views

- No dropdown, make old metadata accessible from the versions list somehow?

- Something else?

**Comment by tcnichol** [comment]
I'm going to create separate issues for each part of this.

**Comment by tcnichol** [comment]
I'm going to create separate issues for each part of this.
