### ISSUE TITLE
UI managing authorization

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#376]
Component that add/remove user to dataset

we have 4 roles:
["owner", "editor", "uploader", "viewer"]

have a dropdown with those 4 options

![Image](https://user-images.githubusercontent.com/13950475/224751361-1fd32487-e8a8-4a8f-a2e5-e1d5d7377a53.png)

For getting the user, you can use this function `getUsersApiV2UsersGet(...)`. We can try a "autocomplete" component given the list of usernames.

For assigning the role, you can use this function `saveAuthorizationApiV2AuthorizationsPost(...)`

**Comment by longshuicy** [comment]
Right now let's enforce some frontend Auth, say only "owner" can assign/manage authorization on resource.

**Comment by arunapa** [comment]
Changes have been merged, marking this task as closed.
