### ISSUE TITLE
large files not uploaded correctly

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder2#39]
I created a dataset with a few files. One of the files (a pdf) when downloaded no longer opens, and is much smaller than it should be.

**Comment by tcnichol** [comment]
I have shared the file on slack. It is too large to upload to the issue.

**Comment by tcnichol** [comment]
Checking minio, the entire files do not seem to upload. The largest files in the db should be 25 and 28 MB, but the largest file in minio clowder bucket is 8 MB.

**Comment by longshuicy** [comment]
fixed
