### ISSUE TITLE
Move groups to the sidebar and figure out how to navigate from group page to all the groups

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#418]
How do we jump from this:
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/13950475/230401316-a0b6751f-0705-4464-82bc-69fe7d9256e4.png">

to 
<img width="1642" alt="image" src="https://user-images.githubusercontent.com/13950475/230401435-c3ff4f4b-54be-49e8-87e7-47c046708d88.png">

**Comment by longshuicy** [comment]
Add a breadcrum on the top to navigate between individual Group ==> Groups

**Comment by longshuicy** [comment]
One example of group
```
{
    "_id" : ObjectId("6419c5c5e402ed1b774f86b8"),
    "creator" : "cwang138@illinois.edu",
    "created" : ISODate("2023-03-21T14:57:09.231+0000"),
    "modified" : ISODate("2023-03-21T14:57:09.231+0000"),
    "name" : "test group 2",
    "description" : "a group is a container of several users",
    "users" : [
        {
            "user" : {
                "id" : ObjectId("64139c240c3c09548e9d7bac"),
                "email" : "cwang138@illinois.edu",
                "first_name" : "Chen",
                "last_name" : "Wang"
            },
            "editor" : true
        },
        {
            "user" : {
                "id" : ObjectId("64148bf20c3c09548e9d7c8f"),
                "email" : "chenwang.carrie@gmail.com",
                "first_name" : "Chen",
                "last_name" : "Wang"
            },
            "editor" : false
        }
    ],
    "views" : NumberInt(0)
}
```

**Comment by arunapa** [comment]
Screenshots from PR:
![Screenshot 2023-04-12 at 9 33 27 PM](https://user-images.githubusercontent.com/28983148/231633554-c0a0e652-47c5-4817-b638-a0d6c6ec4c2b.png)
![Screenshot 2023-04-12 at 9 33 32 PM](https://user-images.gi
![Screenshot 2023-04-12 at 9 33 35 PM](https://user-images.githubusercontent.com/28983148/231633568-cf78329c-01d2-4564-a2ae-c981a0e49e97.png)
thubusercontent.com/28983148/231633559-a030fe93-f6bc-403c-82c9-95dddb263575.png)
