### ISSUE TITLE
Browser back on 403 page takes us to the dataset page we don't have access to

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#438]
If we navigate to a dataset that we don't have access to we are shown a 403 page. If we hit the back button in the browser we are taking to that same dataset page and get an error.

**Comment by lmarini** [comment]
Only happens on beanie branch.

**Comment by longshuicy** [comment]
@arunapa if you finish your tasks on your plate and still have some cycle left, could you also help me on that? Thanks!

**Comment by longshuicy** [comment]
If clicking then switch it to rendering a 403 component 
Otherwise still redirect to the 403 page

**Comment by longshuicy** [comment]
Ideally in the future we can do the same for 404 as well
