### ISSUE TITLE
Frontend need to display more verbose backend error

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#443]
Right now if it's 500 or 400 it just say `internal error` or `bad request` without more information.
Need to display more

**Comment by longshuicy** [comment]
Also the report button title seems not able to parse the correct response body please also check:


![Image](https://user-images.githubusercontent.com/13950475/233135510-d9d20b6a-d2bb-420c-aa69-b9d39919d4d4.png)

**Comment by arunapa** [comment]
Root cause: The onClick event for the report button has a semantic error, which is causing the issue reason string to be replaced with an object. Will push the fix.
