### ISSUE TITLE
Switching PROD/DEV docker compose requires to deleted keycloak volume

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#457]
When we switching from prod docker compose to dev docker compose, it's still using the original keycloak volume.
Check if anything is being cached?

to reproduce login, and check the path to the redirection

**Comment by lmarini** [comment]
Looks like whatever docker compose gets run first, that `KC_DB_URL_DATABASE` gets used to create the container. When the other docker compose is used to start the services, if the postgres volume is already there, it ignores it and doesn't create the other postgres database. So if you start with the production docker compose, you get a `keycloak_prod` created. But when you switch to the dev docker compose, no `keycloak_dev` is created. I tested this by going into the terminal and trying to connect to both databases with `psql -h localhost -U keycloak -d keycloak_dev` and `psql -h localhost -U keycloak -d keycloak_prod`.

**Comment by lmarini** [comment]
Found reasoning. Makes sense. 

> Warning: the Docker specific variables will only have an effect if you start the container with a data directory that is empty; any pre-existing database will be left untouched on container startup.

https://hub.docker.com/_/postgres

**Comment by longshuicy** [comment]
addressed in #565
