### ISSUE TITLE
Confusing error message while trying to update a file with different file name

### ISSUE THREAD

**Issue by ddey2** [clowder-framework/clowder2#520]
1. Upload a file named a3.txt
2. Try updating the above file with a6.txt

It shows and intermediate error message which goes away soon (user can't read it) and then the window shows irrelevant message
<img width="506" alt="Screenshot 2023-06-01 at 4 02 40 PM" src="https://github.com/clowder-framework/clowder2/assets/22405928/b1add66a-9281-4156-b656-def247dac54f">
<img width="1380" alt="Screenshot 2023-06-01 at 4 02 45 PM" src="https://github.com/clowder-framework/clowder2/assets/22405928/7fca3b7e-b2b6-4b36-9a8c-3fbf302a2670">

**Comment by longshuicy** [comment]
That might be related to what backend return as a error message. Frontend just display the response message now

**Comment by ddey2** [comment]
True. I can take a look at the backend. I will assign this to myself.
