### ISSUE TITLE
Unnecessary Error message on Extraction history in Beanie branch

### ISSUE THREAD

**Issue by ddey2** [clowder-framework/clowder2#523]
Steps to reproduce:
1. Start fresh with db and docker volume
2. Upload a dataset and a new file
3. Go to the usermetadata or Extracted Metadata tab. It shows unnecessary error message as shown in screenshot. There is no metadata available, so it shouldn't try to load it from backend.
<img width="1728" alt="Screenshot 2023-06-05 at 6 47 12 AM" src="https://github.com/clowder-framework/clowder2/assets/22405928/65f8f3b5-8e1c-4b8c-bdfe-814b1101ac81">
<img width="1728" alt="Screenshot 2023-06-05 at 6 47 23 AM" src="https://github.com/clowder-framework/clowder2/assets/22405928/08d94bba-6cfc-42aa-88c9-d56f979ee95b">

**Comment by longshuicy** [comment]
@max-zilla could you verify and see if it's already resolved?

**Comment by longshuicy** [comment]
Looks like this is still an issue
