### ISSUE TITLE
Extraction doesn't work

### ISSUE THREAD

**Issue by ddey2** [clowder-framework/clowder2#544]
<img width="1252" alt="Screenshot 2023-06-09 at 6 55 58 AM" src="https://github.com/clowder-framework/clowder2/assets/22405928/598aac5f-404f-4cd3-94bd-53cb3b60a72a">
<img width="1707" alt="Screenshot 2023-06-09 at 6 55 51 AM" src="https://github.com/clowder-framework/clowder2/assets/22405928/e3ba93e9-64dc-4ac0-95b2-adede33716fd">

**Comment by ddey2** [comment]
<img width="1085" alt="Screenshot 2023-06-09 at 7 37 12 AM" src="https://github.com/clowder-framework/clowder2/assets/22405928/488c48dc-634e-45fd-b125-dcd498161867">

**Comment by longshuicy** [comment]
@ddey2 Could you check if this is still an issue. If not could you close it? Thanks!

**Comment by ddey2** [comment]
Today I confirmed that there is still an error in main branch when I try to submit a file for extraction. Since we merged beanie branch, I checked this on main.

<img width="1008" alt="Screenshot 2023-07-19 at 10 48 36 AM" src="https://github.com/clowder-framework/clowder2/assets/22405928/93f146c7-2f7e-4d8b-9e6f-59e034ee6344">
<img width="1181" alt="Screenshot 2023-07-19 at 10 48 44 AM" src="https://github.com/clowder-framework/clowder2/assets/22405928/d0a8c7a1-e2b1-4e01-af25-415594f3c53f">

**Comment by ddey2** [comment]
I checked out a new branch to work on this. I see the error no more. I again checked on main branch, no error. I may not have pulled in the latest changes on main branch, that explains the discrepancies. Sorry for the confusion. I will close this.

This was addressed in https://github.com/clowder-framework/clowder2/pull/568/files#diff-c20cec5adb3c20f01d83c7b036ac5eab55e8eb4d91929fb4106a336f2378e98
