### ISSUE TITLE
Preview for image extractor

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder2#555]
Add image extractor preview using viz config and viz data.

**Comment by longshuicy** [comment]
Might need to use pyclowder v2 will be addressed in task 70

**Comment by longshuicy** [comment]
can reuse binary extractor example

**Comment by sandeep-ps** [comment]
I believe this task can be closed, as it's being addressed via https://github.com/clowder-framework/extractors-core/tree/34-creating-extractors-core-from-v1-to-v2. I will try to create a PR on Friday.
