### ISSUE TITLE
New Dataset Finish button never enables

### ISSUE THREAD

**Issue by max-zilla** [clowder-framework/clowder2#625]
Created two metadata fields, both required, but even when I fill them out on New Dataset page the button never enables:
![image](https://github.com/clowder-framework/clowder2/assets/14166971/10ca9433-776d-4e35-8ad7-1b76f633bf22)

There isn't a way in the UI I've found to modify or delete metadata definitions, either.

**Comment by tcnichol** [comment]
I have a branch and am looking into this.

**Comment by tcnichol** [comment]
The problem here seems to be using .every instead of .map.

Using .map seems to work.
