### ISSUE TITLE
Raw byte size limit when visualize 

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#647]
Set a limit when visualizing the raw bytes so large file doesn't get visualized

- Set a threshold instance wide
- Backend endpoint to provide bytes to frontend
    - If there is vis config, provide from visualization bytes
    - If there isn't provide the raw bytes
    - The cutoff can be handled by this endpoint.
    - The endpoint can give messages indicate that threshold is over

**Comment by lmarini** [comment]
@tcnichol , @ddey2 is going to take a look at this one.
