### ISSUE TITLE
Double check pytest upload file test

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#659]
Make sure the bytes actually end up in minio.

**Comment by tcnichol** [comment]
I have checked this and can confirm the bytes are in Minio.

I ran tests, and before upload_file was called, I checked the bucket and it had 2 files.

After that method, there was a new file that was 34 bytes, the size of the file uploaded in tests. 

If this is enough testing, we can mark this one closed. Let me know if I should test any further.
