### ISSUE TITLE
Download button text disappears at small widths

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#679]
<img width="227" alt="Screenshot 2023-08-28 at 1 22 08 PM" src="https://github.com/clowder-framework/clowder2/assets/599725/5ce4e001-9892-41ad-993f-f495fdc47b20">

**Comment by tcnichol** [comment]
Currently working on moving the ActionsMenu and FileActionsMenu. If a dataset name is long, the buttons end up being cut off, same with the file name. 

Right now the elements are cluttered and the spacing and placement are not consistent,  need to fix that.

**Comment by tcnichol** [comment]
<img width="931" alt="Screenshot 2023-09-06 at 2 02 29 PM" src="https://github.com/clowder-framework/clowder2/assets/40038535/e5925be0-8f4b-4312-b624-dc310280a680">

Here is sort of what I am trying to do with dataset. If the name of the dataset was longer, the button was almost always cut off and there really isn't enough room. Moving the ActionsMenu but elements aren't aligned right yet.

**Comment by tcnichol** [comment]
Note - I thought that my changes had accidentally moved the DatasetDetails to the bottom of the page, but that appears on main as well.
