### ISSUE TITLE
Dowload link error on dataset list page

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#691]
Probably since the switch to opening a new tab. To reproduce, clicking on download link on dataset list page throws a `Internal Server Error`.

**Comment by KastanDay** [comment]
Possibly related to dataset "download" button missing padding in CSS.

![CleanShot 2023-09-05 at 08 36 03](https://github.com/clowder-framework/clowder2/assets/13607221/4629eb05-1b47-454d-93ce-a5ccdaa087c0)
