### ISSUE TITLE
github action for black linting checking the scripts folder

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#703]
It should only check `backend` folder but somehow there is a failing github action 
https://github.com/clowder-framework/clowder2/actions/runs/6029997653/job/16549846647?pr=681

**Comment by tcnichol** [comment]
I think I found a fix for this, I created a pull request but we should probably see if the change works for the github action on Luigi's pull request here:

https://github.com/clowder-framework/clowder2/pull/681
