### ISSUE TITLE
Update file broken

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#714]
There are 2 issues:

1. update file broken:
<img width="755" alt="image" src="https://github.com/clowder-framework/clowder2/assets/13950475/865ed42c-0296-4c5c-9345-dae6adddcd1e">

2. After dismiss the error and update successfully, the "version pill" doesn't reflect the change immediate. You have to refresh to see it reflect. Suspect some async condition or not using the latest redux state

**Comment by ddey2** [comment]
Don't see this error now in main

**Comment by longshuicy** [comment]
<img width="639" alt="image" src="https://github.com/clowder-framework/clowder2/assets/13950475/1e3deee5-3ddc-4a14-88ac-8200b3284c4f">

im seeing this again

**Comment by longshuicy** [comment]
<img width="1516" alt="image" src="https://github.com/clowder-framework/clowder2/assets/13950475/e36908be-d04b-497d-a392-93af5b3a586a">

This button is broken too

**Comment by longshuicy** [comment]
Another interesting behavior that im not sure about is:
1. When switch the current version to a previous one (click that version pill)
2. Then click update file 
3. It immediately flip to the latest version.

**Comment by ddey2** [comment]
To me, if I am updating a file, that means I want to see the updated version. I can see if it's confusing to some users.
