### ISSUE TITLE
Sharing tab bugs

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#735]
1. When sharing with a user --> then on the sharing tab change the user's privilege to something else --> refresh the page. The user is gone.
2. When change the privilege of a group, there is backend failure bug
<img width="1468" alt="image" src="https://github.com/clowder-framework/clowder2/assets/13950475/e2a6510a-05eb-452e-83b1-a7c208814e8c">

**Comment by tcnichol** [comment]
The backend bug for changing group role should be fixed. A method was being sent the wrong arguments so the elasticsearch index was failing.
