### ISSUE TITLE
Fix failing github tests

### ISSUE THREAD

**Issue by longshuicy** [clowder-framework/clowder2#74]
@github-actions
Backend Lint / lint (pull_request) Failing after 18s — lint
[Details](https://github.com/clowder-framework/clowder2/runs/8076095340?check_suite_focus=true)
@github-actions
Pytest / test (push) Failing after 3m — test

**Comment by lmarini** [comment]
Connection between python pytest and keycloak is not working. Either the port is wrong or the Keycloak frontend URL is not properly set.

**Comment by lmarini** [comment]
Connection between python pytest and keycloak is not working. Either the port is wrong or the Keycloak frontend URL is not properly set.
