### ISSUE TITLE
Test database should be emptied before each run of pytest

### ISSUE THREAD

**Issue by max-zilla** [clowder-framework/clowder2#75]
The clowder testing mongoDB does not get cleaned before a new test run, which can lead to unexpected errors in testing when resources (e.g. metadata definitions) already exist from previous tests.

https://github.com/clowder-framework/clowder2/blob/main/backend/app/tests/conftest.py#L19

I've tried a bit to use fixtures to perform this task before each run, but no success so far.

**Comment by tcnichol** [comment]
Will start on this one for Monday.

**Comment by tcnichol** [comment]
Pull request is open and ready for review.
