### ISSUE TITLE
Stretched icon on submit to extractor list

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#768]
<img width="871" alt="Screenshot 2023-10-03 at 3 43 46 PM" src="https://github.com/clowder-framework/clowder2/assets/599725/599f5fd6-785e-4c69-b8b8-a52be5f51e83">

**Comment by tcnichol** [comment]
For this issue, I am having a hard time styling the ripple effect, so I took it out in the draft pull request. Will discuss in meeting Thursday or Friday.
