### ISSUE TITLE
Version number overlaps page elements

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder2#948]
Ideally it should be part of the page and just show at the bottom. If not, maybe we should just remove it from the page.

<img width="270" alt="Screenshot 2024-02-29 at 11 56 39 AM" src="https://github.com/clowder-framework/clowder2/assets/599725/7b8cfe3f-e83f-49ae-862f-49007fef905f">

**Comment by longshuicy** [comment]
Closing this issue. Will address improvement in the footer issue https://github.com/clowder-framework/clowder2/issues/961
